In [3]:
a=20
b=30
print(a+b)
a

50


20

In [1]:
print("hello")

hello


In [4]:
var=input("Enter")

In [1]:
import numpy as np

1D Arrays

In [8]:
arr1=np.array([1,2,3,4,5])
arr2=arr1*10
arr1[2:4]=[20,30]
arr1

array([ 1,  2, 20, 30,  5])

2D Arrays

In [11]:
arr2=np.array([[1,2,3,4],[5,4,9,8],[8,9,2000,5],[2,5,8,7]])
arr2.shape
arr2.size
arr2[1:3,1:3]
arr2

array([[   1,    2,    3,    4],
       [   5,    4,    9,    8],
       [   8,    9, 2000,    5],
       [   2,    5,    8,    7]])

In [24]:
arr3=np.array([[1,2,3],[5,7,8],[4,8,2],[8,2,6],[2,4,8],[8,3,5],[4,5,2]])
arr3.shape
arr3[:,::2]
arr3[0::6,0::2]=-1
arr3

array([[-1,  2, -1],
       [ 5,  7,  8],
       [ 4,  8,  2],
       [ 8,  2,  6],
       [ 2,  4,  8],
       [ 8,  3,  5],
       [-1,  5, -1]])

Advanced Indexing

In [32]:
arr3[[0,1,4]]=-255
arr3

array([[-255, -255, -255],
       [-255, -255, -255],
       [   4,    8,    2],
       [   8,    2,    6],
       [-255, -255, -255],
       [   8,    0,    5],
       [  -1,    5,   -1]])

Boolian Indexing

In [36]:
arr3[arr3<50]=0
arr3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
arr = np.array([12, 45, 7, 19, 34, 28, 90, 55, 63])
